import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { CartProvider } from '@/context/CartContext'
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider> 
    <html lang="en">

      <body className={inter.className}>
      <ClerkLoading>loading....</ClerkLoading>
      <ClerkLoaded>
        <CartProvider>
        <div>
        <Navbar/>
        </div>
        {children}
        <div>
        <Footer/>
        </div>
        </CartProvider>
        </ClerkLoaded>
      </body>
    </html>
    
    </ClerkProvider>
  )
}
